# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rparsertools_wrappers", use_symbols = TRUE, package_name = "rparsertools")

#' @docType package
#' @usage NULL
#' @useDynLib rparsertools, .registration = TRUE
NULL

parse_package_dependencies <- function(package, deps) .Call(wrap__parse_package_dependencies, package, deps)

parse_all_package_dependencies <- function(packages, deps) .Call(wrap__parse_all_package_dependencies, packages, deps)


# nolint end
