[package]
name = 'rparsertools'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rparsertools'

[dependencies]
debcontrol = "0.1.1"
debian-control = "0.1.7"
extendr-api = '*'
nom = "7.1.3"
